In [33]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import LabelEncoder,MinMaxScaler, RobustScaler,OneHotEncoder, StandardScaler
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import root_mean_squared_error, r2_score, accuracy_score,classification_report, roc_auc_score, precision_score, recall_score, confusion_matrix

In [3]:
df = pd.read_csv("data.csv")
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K


In [8]:
X = df.drop('income', axis=1)
y = df['income']

In [9]:
num_features = X.select_dtypes(include=['int64','float64']).columns
cat_features = X.select_dtypes(include=['object']).columns

In [57]:
preprocessor = ColumnTransformer(
transformers=[
('num', StandardScaler(), num_features),
('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False),
cat_features)
])
clf = Pipeline([
('preprocessor', preprocessor),
('classifier', DecisionTreeClassifier(max_depth=10, random_state=0))
])

clf_logreg = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier',  LogisticRegression(solver='lbfgs', max_iter=1000,random_state=42))
])

clf_rf = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier',  RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42))
])





In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y,
random_state=42)
clf_rf.fit(X_train, y_train)
y_pred_rf = clf_rf.predict(X_test)

In [59]:
print(f"Accuracy:  {accuracy_score(y_test, y_pred):.3f}")
print(f"Precision: {precision_score(y_test, y_pred,average='macro'):.3f}")
print(f"Recall:    {recall_score(y_test, y_pred,average='macro'):.3f}")
print(f"Matriz de confusión:\n{confusion_matrix(y_test, y_pred)}")


Accuracy:  0.593
Precision: 0.594
Recall:    0.400
Matriz de confusión:
[[7088   12  311    5]
 [3247  319  149   16]
 [1062    8 1240   42]
 [ 513   24  582   35]]
